export const FETCH_ALL_ARTICLES_REQUEST = 'FETCH_ALL_ARTCILES_REQUEST';
export const FETCH_ALL_ARTICLES_SUCCESS = 'FETCH_ALL_ARTCILES_SUCCESS';
export const FETCH_ALL_ARTICLES_FAILURE = 'FETCH_ALL_ARTCILES_FAILURE';

export const FETCH_TOPICS_REQUEST = 'FETCH_TOPICS_REQUEST';
export const FETCH_TOPICS_SUCCESS = 'FETCH_TOPICS_SUCCESS';
export const FETCH_TOPICS_FAILURE = 'FETCH_TOPICS_FAILURE';