export const FETCH_ALL_ARTICLES_REQUEST = 'FETCH_ALL_ARTCILES_REQUEST';
export const FETCH_ALL_ARTICLES_SUCCESS = 'FETCH_ALL_ARTCILES_SUCCESS';
export const FETCH_ALL_ARTICLES_FAILURE = 'FETCH_ALL_ARTCILES_FAILURE';